GSM_ALGHORITM_BUFFER                    EQU             0xA867B35C
off_A84F6208                            EQU             0xA867B1CC
RAM_F14                                 EQU             0xA8639C4E
RAM_SPN                                 EQU             0xA8639C24
RAM_IMSI                                EQU             0xA863987E
RAM_LOCI                                EQU             0xA8639887
RAM_FPLMN                               EQU             0xA86398C2

LAST_SIM_BUF_POINTER                    EQU             0xA8639E90
LAST_LGP_BUF                            EQU             0xA8634010
RAM_STBY                                EQU             0xA863A518