GSM_ALGHORITM_BUFFER                    EQU             0xA84F5550
off_A84F6208                            EQU             0xA84F53C0
RAM_F14                                 EQU             0xA84C12FA
RAM_SPN                                 EQU             0xA84C12D0
RAM_IMSI                                EQU             0xA84C0F2A
RAM_LOCI                                EQU             0xA84C0F33
RAM_FPLMN                               EQU             0xA84C0F6E

LAST_SIM_BUF_POINTER                    EQU             0xA84C153C
LAST_LGP_BUF                            EQU             0xA84AE130
RAM_STBY                                EQU             0xA84C1BD4