GSM_ALGHORITM_BUFFER                    EQU             0xA84F6398
off_A84F6208                            EQU             0xA84F6208
RAM_F14                                 EQU             0xA84BF65E
RAM_SPN                                 EQU             0xA84BF634
RAM_IMSI                                EQU             0xA84BF28E
RAM_LOCI                                EQU             0xA84BF297
RAM_FPLMN                               EQU             0xA84BF2D2

LAST_SIM_BUF_POINTER                    EQU             0xA84BF8A0
LAST_LGP_BUF                            EQU             0xA84AE130
RAM_STBY                                EQU             0xA84BFF30
