GSM_ALGHORITM_BUFFER                    EQU             0xA86CD590
off_A84F6208                            EQU             0xA86CD400
RAM_F14                                 EQU             0xA868BE66
RAM_SPN                                 EQU             0xA868BE3C
RAM_IMSI                                EQU             0xA868BA96
RAM_LOCI                                EQU             0xA868BA9F
RAM_FPLMN                               EQU             0xA868BADA

LAST_SIM_BUF_POINTER                    EQU             0xA868C0A8
LAST_LGP_BUF                            EQU             0xA8686010
RAM_STBY                                EQU             0xA868C730
